// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Caml_obj from "bs-platform/lib/es6/caml_obj.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

function validatedFriendToJs(param) {
  return {
          name: param[/* name */0],
          age: param[/* age */1],
          email: param[/* email */2]
        };
}

function validatedFriendFromJs(param) {
  return /* record */[
          /* name */param.name,
          /* age */param.age,
          /* email */param.email
        ];
}

var emptyFriend = /* record */[
  /* name */"",
  /* age */"",
  /* email */""
];

function toUnvalidated(param) {
  return /* record */[
          /* name */param[/* name */1],
          /* age */String(param[/* age */2]),
          /* email */param[/* email */3]
        ];
}

var component = ReasonReact.reducerComponentWithRetainedProps("FriendForm");

function make($staropt$star, handleSubmit, _children) {
  var initState = $staropt$star !== undefined ? $staropt$star : emptyFriend;
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */(function (self) {
              Caml_obj.caml_equal(self[/* retainedProps */2], initState);
              return initState;
            }),
          /* didMount */(function (param) {
              console.log("Mounted");
              return /* () */0;
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1];
              return React.createElement("form", {
                          onSubmit: (function (e) {
                              e.preventDefault();
                              return Curry._1(self[/* send */3], /* Submit */0);
                            })
                        }, React.createElement("div", {
                              className: "input-container"
                            }, React.createElement("label", undefined, "Name", React.createElement("input", {
                                      value: match[/* name */0],
                                      onChange: (function (e) {
                                          return Curry._1(self[/* send */3], /* ChangeField */[
                                                      /* Name */0,
                                                      e.target.value
                                                    ]);
                                        })
                                    })), React.createElement("label", undefined, "Age", React.createElement("input", {
                                      value: match[/* age */1],
                                      onChange: (function (e) {
                                          return Curry._1(self[/* send */3], /* ChangeField */[
                                                      /* Age */1,
                                                      e.target.value
                                                    ]);
                                        })
                                    })), React.createElement("label", undefined, "Email", React.createElement("input", {
                                      value: match[/* email */2],
                                      onChange: (function (e) {
                                          return Curry._1(self[/* send */3], /* ChangeField */[
                                                      /* Email */2,
                                                      e.target.value
                                                    ]);
                                        })
                                    }))), React.createElement("button", undefined, "Submit"));
            }),
          /* initialState */(function (param) {
              return emptyFriend;
            }),
          /* retainedProps */initState,
          /* reducer */(function (action, state) {
              if (action) {
                switch (action[0]) {
                  case 0 : 
                      return /* Update */Block.__(0, [/* record */[
                                  /* name */action[1],
                                  /* age */state[/* age */1],
                                  /* email */state[/* email */2]
                                ]]);
                  case 1 : 
                      return /* Update */Block.__(0, [/* record */[
                                  /* name */state[/* name */0],
                                  /* age */action[1],
                                  /* email */state[/* email */2]
                                ]]);
                  case 2 : 
                      return /* Update */Block.__(0, [/* record */[
                                  /* name */state[/* name */0],
                                  /* age */state[/* age */1],
                                  /* email */action[1]
                                ]]);
                  
                }
              } else {
                Curry._1(handleSubmit, state);
                return /* Update */Block.__(0, [emptyFriend]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

export {
  validatedFriendToJs ,
  validatedFriendFromJs ,
  emptyFriend ,
  toUnvalidated ,
  component ,
  make ,
  
}
/* component Not a pure module */
