// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

var component = ReasonReact.statelessComponent("FriendsList");

function friendToJs(param) {
  return {
          id: param[/* id */0],
          name: param[/* name */1],
          age: param[/* age */2],
          email: param[/* email */3]
        };
}

function friendFromJs(param) {
  return /* record */[
          /* id */param.id,
          /* name */param.name,
          /* age */param.age,
          /* email */param.email
        ];
}

function make(data, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("table", {
                          className: "friends"
                        }, React.createElement("thead", undefined, React.createElement("tr", undefined, /* array */[
                                    "Delete",
                                    "Edit",
                                    "Name",
                                    "Age",
                                    "Email"
                                  ].map((function (field) {
                                        return React.createElement("th", undefined, field);
                                      })))), React.createElement("tbody", undefined, data.map((function (param) {
                                    return React.createElement("tr", {
                                                key: String(param[/* id */0])
                                              }, React.createElement("td", undefined, React.createElement("button", {
                                                        className: "danger"
                                                      }, "Delete")), React.createElement("td", undefined, React.createElement("button", undefined, "Edit")), React.createElement("td", undefined, param[/* name */1]), React.createElement("td", undefined, String(param[/* age */2])), React.createElement("td", undefined, param[/* email */3]));
                                  }))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

export {
  component ,
  friendToJs ,
  friendFromJs ,
  make ,
  
}
/* component Not a pure module */
