/* TypeScript file generated by genType. */

// tslint:disable-next-line:no-var-requires
const Curry = require('bs-platform/lib/es6/curry.js');

// tslint:disable-next-line:no-var-requires
const FriendFormBS = require('./FriendForm.bs');

// tslint:disable-next-line:no-var-requires
const ReasonReact = require('reason-react/src/ReasonReact.js');

// tslint:disable-next-line:interface-over-type-literal
export type Props = {
  readonly name: string; 
  readonly age: string; 
  readonly email: string; 
  readonly handleSubmit: (_1:{
    readonly age: string; 
    readonly email: string; 
    readonly name: string
  }) => unknown; 
  readonly children?: unknown
};

export const FriendForm: React.ComponentClass<Props> = ReasonReact.wrapReasonForJs(
  FriendFormBS.component,
  (function _(jsProps: Props) {
     return Curry._5(FriendFormBS.make, jsProps.name, jsProps.age, jsProps.email, jsProps.handleSubmit, jsProps.children);
  }));

export default FriendForm;
