/* TypeScript file generated by genType. */

// tslint:disable-next-line:no-var-requires
const Curry = require('bs-platform/lib/es6/curry.js');

// tslint:disable-next-line:no-var-requires
const FriendsListBS = require('./FriendsList.bs');

// tslint:disable-next-line:no-var-requires
const ReasonReact = require('reason-react/src/ReasonReact.js');

// tslint:disable-next-line:interface-over-type-literal
export type friend = {
  readonly id: number; 
  readonly name: string; 
  readonly age: number; 
  readonly email: string
};

// tslint:disable-next-line:interface-over-type-literal
export type Props = {
  readonly data: friend[]; 
  readonly handleEdit: (_1:friend) => void; 
  readonly children?: unknown
};

export const FriendsList: React.ComponentClass<Props> = ReasonReact.wrapReasonForJs(
  FriendsListBS.component,
  (function _(jsProps: Props) {
     return Curry._3(FriendsListBS.make, jsProps.data.map(function _element(ArrayItem: any) { return [ArrayItem.id, ArrayItem.name, ArrayItem.age, ArrayItem.email]}), function _(Arg1: any) {
  const result = jsProps.handleEdit({id:Arg1[0], name:Arg1[1], age:Arg1[2], email:Arg1[3]});
  return result
}, jsProps.children);
  }));

export default FriendsList;
