// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Axios from "axios";
import * as React from "react";
import * as Json_decode from "@glennsl/bs-json/src/Json_decode.bs.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as FriendsList$Friends from "./FriendsList.bs.js";
import * as Caml_builtin_exceptions from "bs-platform/lib/es6/caml_builtin_exceptions.js";

function friend(json) {
  return /* record */[
          /* id */Json_decode.field("id", Json_decode.$$int, json),
          /* name */Json_decode.field("name", Json_decode.string, json),
          /* age */Json_decode.field("age", Json_decode.$$int, json),
          /* email */Json_decode.field("email", Json_decode.string, json)
        ];
}

var Decode = /* module */[/* friend */friend];

var apiEndpoint = "http://10.0.0.53:5000/friends";

var component = ReasonReact.reducerComponent("ReasonApp");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (param) {
              return Curry._1(param[/* send */3], /* GetFriends */0);
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              var state = param[/* state */1];
              if (typeof state === "number") {
                if (state !== 0) {
                  throw [
                        Caml_builtin_exceptions.match_failure,
                        /* tuple */[
                          "ReasonApp.re",
                          70,
                          29
                        ]
                      ];
                } else {
                  return React.createElement("div", undefined, "Loading");
                }
              } else {
                return ReasonReact.element(undefined, undefined, FriendsList$Friends.make(state[0], /* array */[]));
              }
            }),
          /* initialState */(function (_state) {
              return /* Loading */0;
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _state) {
              if (typeof action === "number") {
                if (action === 0) {
                  return /* UpdateWithSideEffects */Block.__(2, [
                            /* Loading */0,
                            (function (self) {
                                Axios.get(apiEndpoint).then((function (response) {
                                          var data = response.data;
                                          var fs = Json_decode.array(friend, (console.log(data), data));
                                          return Promise.resolve(Curry._1(self[/* send */3], /* FriendsGot */Block.__(0, [fs])));
                                        })).catch((function (err) {
                                        return Promise.resolve((console.log(err), /* () */0));
                                      }));
                                return /* () */0;
                              })
                          ]);
                } else {
                  throw [
                        Caml_builtin_exceptions.match_failure,
                        /* tuple */[
                          "ReasonApp.re",
                          35,
                          31
                        ]
                      ];
                }
              } else if (action.tag) {
                throw [
                      Caml_builtin_exceptions.match_failure,
                      /* tuple */[
                        "ReasonApp.re",
                        35,
                        31
                      ]
                    ];
              } else {
                return /* Update */Block.__(0, [/* Loaded */[action[0]]]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var jsComponent = ReasonReact.wrapReasonForJs(component, (function (_jsProps) {
        return make(/* array */[]);
      }));

export {
  Decode ,
  apiEndpoint ,
  component ,
  make ,
  jsComponent ,
  
}
/* component Not a pure module */
