// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Axios from "axios";
import * as React from "react";
import * as Caml_format from "bs-platform/lib/es6/caml_format.js";
import * as Json_decode from "@glennsl/bs-json/src/Json_decode.bs.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as FriendForm$Friends from "./FriendForm.bs.js";
import * as FriendsList$Friends from "./FriendsList.bs.js";

(( require("./App.scss") ));

function friend(json) {
  return /* record */[
          /* id */Json_decode.field("id", Json_decode.$$int, json),
          /* name */Json_decode.field("name", Json_decode.string, json),
          /* age */Json_decode.field("age", Json_decode.$$int, json),
          /* email */Json_decode.field("email", Json_decode.string, json)
        ];
}

var Decode = /* module */[/* friend */friend];

var apiEndpoint = "http://10.0.0.53:5000/friends";

var component = ReasonReact.reducerComponent("ReasonApp");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (param) {
              return Curry._1(param[/* send */3], /* GetFriends */0);
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              var send = param[/* send */3];
              var state = param[/* state */1];
              var match = state[0];
              var tmp;
              if (typeof match === "number") {
                tmp = React.createElement("div", undefined, "Loading");
              } else if (match.tag) {
                var e = state[1];
                var tmp$1;
                if (e) {
                  var f = e[0];
                  tmp$1 = ReasonReact.element(undefined, undefined, FriendForm$Friends.make(FriendForm$Friends.toUnvalidated(f), (function (param) {
                              return Curry._1(send, /* PutFriend */Block.__(3, [
                                            f[/* id */0],
                                            /* record */[
                                              /* name */param[/* name */0],
                                              /* age */Caml_format.caml_int_of_string(param[/* age */1]),
                                              /* email */param[/* email */2]
                                            ]
                                          ]));
                            }), /* array */[]));
                } else {
                  tmp$1 = ReasonReact.element(undefined, undefined, FriendForm$Friends.make(undefined, (function (param) {
                              return Curry._1(send, /* PostFriend */Block.__(1, [/* record */[
                                              /* name */param[/* name */0],
                                              /* age */Caml_format.caml_int_of_string(param[/* age */1]),
                                              /* email */param[/* email */2]
                                            ]]));
                            }), /* array */[]));
                }
                tmp = React.createElement(React.Fragment, undefined, ReasonReact.element(undefined, undefined, FriendsList$Friends.make(match[0], (function (f) {
                                return Curry._1(send, /* EditFriend */Block.__(2, [f]));
                              }), /* array */[])), tmp$1);
              } else {
                tmp = React.createElement("div", undefined, "Error");
              }
              return React.createElement("main", {
                          className: "App"
                        }, tmp);
            }),
          /* initialState */(function (param) {
              return /* tuple */[
                      /* Loading */0,
                      /* EditingNew */0
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, param) {
              var s = param[0];
              if (typeof action === "number") {
                return /* UpdateWithSideEffects */Block.__(2, [
                          /* tuple */[
                            /* Loading */0,
                            /* EditingNew */0
                          ],
                          (function (param) {
                              var send = param[/* send */3];
                              Axios.get(apiEndpoint).then((function (response) {
                                        var fs = Json_decode.array(friend, response.data);
                                        return Promise.resolve(Curry._1(send, /* FriendsGot */Block.__(0, [fs])));
                                      })).catch((function (err) {
                                      return Promise.resolve(Curry._1(send, /* GotError */Block.__(5, [err])));
                                    }));
                              return /* () */0;
                            })
                        ]);
              } else {
                switch (action.tag | 0) {
                  case 0 : 
                      return /* Update */Block.__(0, [/* tuple */[
                                  /* Loaded */Block.__(1, [action[0]]),
                                  /* EditingNew */0
                                ]]);
                  case 1 : 
                      var f = action[0];
                      return /* UpdateWithSideEffects */Block.__(2, [
                                /* tuple */[
                                  s,
                                  /* EditingNew */0
                                ],
                                (function (param) {
                                    var send = param[/* send */3];
                                    Axios.post(apiEndpoint, FriendForm$Friends.validatedFriendToJs(f)).then((function (response) {
                                              var fs = Json_decode.array(friend, response.data);
                                              return Promise.resolve(Curry._1(send, /* FriendsGot */Block.__(0, [fs])));
                                            })).catch((function (err) {
                                            return Promise.resolve(Curry._1(send, /* GotError */Block.__(5, [err])));
                                          }));
                                    return /* () */0;
                                  })
                              ]);
                  case 2 : 
                      return /* Update */Block.__(0, [/* tuple */[
                                  s,
                                  /* EditingExistent */[action[0]]
                                ]]);
                  case 3 : 
                      var f$1 = action[1];
                      var id = action[0];
                      return /* UpdateWithSideEffects */Block.__(2, [
                                /* tuple */[
                                  s,
                                  /* EditingNew */0
                                ],
                                (function (param) {
                                    var send = param[/* send */3];
                                    Axios.put(apiEndpoint + ("/" + String(id)), FriendForm$Friends.validatedFriendToJs(f$1)).then((function (response) {
                                              var fs = Json_decode.array(friend, response.data);
                                              return Promise.resolve(Curry._1(send, /* FriendsGot */Block.__(0, [fs])));
                                            })).catch((function (err) {
                                            return Promise.resolve(Curry._1(send, /* GotError */Block.__(5, [err])));
                                          }));
                                    return /* () */0;
                                  })
                              ]);
                  case 4 : 
                      return /* NoUpdate */0;
                  case 5 : 
                      return /* Update */Block.__(0, [/* tuple */[
                                  /* Error */Block.__(0, [action[0]]),
                                  /* EditingNew */0
                                ]]);
                  
                }
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var jsComponent = ReasonReact.wrapReasonForJs(component, (function (_jsProps) {
        return make(/* array */[]);
      }));

export {
  Decode ,
  apiEndpoint ,
  component ,
  make ,
  jsComponent ,
  
}
/*  Not a pure module */
